#!/bin/bash

# Stops the script if you aren't running it as root.
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo "************************************"
echo "CREATING CHROOT FOR CORE SWIFT LINUX"

export SUBDIR_CORE="chroot_core"
export DIR_BOOTSTRAP_CORE=$DIR_BUILD/$SUBDIR_CORE
#+++++++++++++++++++++++++++++++++++++++++++++++++
# Enable the following command for production mode
#sh $DIR_REMASTER/create_chroot_core

echo "FINISHED CREATING CHROOT FOR CORE SWIFT LINUX"
echo "*********************************************"

echo "*************************************"
echo "UPDATING SETTINGS IN CORE SWIFT LINUX"



echo "FINISHED UPDATING SETTINGS IN CORE SWIFT LINUX"
echo "**********************************************"

echo "**********************************************"
echo "CREATING CHROOT FOR DIET SWIFT LINUX"
export SUBDIR_DIET="chroot_diet"
export DIR_CHROOT_DIET=$DIR_BUILD/$SUBDIR_DIET
#++++++++++++++++++++++++++++++++++++++++++++++++++++++
# The following line must be enabled in production mode
sh $DIR_REMASTER/create_chroot_diet

echo "FINISHED CREATING CHROOT FOR DIET SWIFT LINUX"
echo "*********************************************"

# Wrap up
#+++++++++++++++++++++++++++++++++++++++++++++++++
# Enable the following command for production mode
# chown -R $SUDO_USER:users $DIR_BUILD
